version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/pwa-rails
    image: pwa-rails:latest
    command: bundle exec rails s -u puma -p 3000 -b '0.0.0.0'
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15.1
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust